version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
shallow_clone: true
before_build:
- cmd: nuget restore
build:
  project: ThmTool.sln
  verbosity: minimal
after_build:
- cmd: >-
    cd ThmTool\bin\%CONFIGURATION%

    7z a ..\..\..\%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%.7z .\

    cd ..\..\..\

    appveyor PushArtifact %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%.7z %CONFIGURATION%
artifacts:
- path: $(appveyor_project_name)_$(appveyor_build_version).7z
  name: $(configuration)
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: fCUuoKt+E+BdDL+sDGj7wROcLX7DNPC8jXazUC52F3HerLnlIrHKv/pTr7OURHaC
  repository: OGSR/ThmTool
  artifact: Release
  force_update: true
  on:
    appveyor_repo_tag: true